export enum ScreenType {
    START_MENU = 'start_menu',
    MENU = 'menu',
    MANOR = 'manor',
    WORLD_MAP = 'world_map',
    HEROES = 'heroes',
    CAPTIVES = 'captives',
    SERVANTS = 'servants',
    INVENTORY = 'inventory',
    ITEM_LIBRARY = 'item_library',
    EVENT = 'event',
    SCENE = 'scene',
    PC_PROFILE = 'pc_profile',
    CONVERSION = 'conversion',
    EXPLORE = 'explore',
    QUESTS = 'quests',
    TURN_SUMMARY = 'turn_summary',
}
